name: awesome_ext
description: Extends for plugin.
version: 0.0.2
author: CodingShuuu<codingshuuu@gmail.com>
homepage: https://github.com/codingshuuu/flutter_ext.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  # https://pub.dev/packages/flustars_flutter3
  flustars_flutter3: ^3.0.0
  # https://github.com/dart-lang/i18n/tree/main/pkgs/intl
  intl: ^0.18.1
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.2
  uuid: ^3.0.4
  md5_file_checksum: ^1.0.4
  device_info_plus: ^3.2.3
  package_info_plus: ^1.0.6
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^4.0.2
  logger: ^2.0.2
  path_provider: ^2.0.5
  sp_util: ^2.0.0
  crypto: ^3.0.1
  convert: ^3.0.1
  path: ^1.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
