name: awesome_ext
description: Extends for plugin.
version: 0.0.4
#author: CodingShuuu<codingshuuu@gmail.com>
homepage: https://github.com/codingshuuu/flutter_ext.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  # https://pub.dev/packages/flustars_flutter3
  flustars_flutter3: ^3.0.0
  # https://github.com/dart-lang/i18n/tree/main/pkgs/intl
  intl: ^0.18.1
  url_launcher: ^6.1.14
  fluttertoast: ^8.2.2
  uuid: ^4.0.0
  md5_file_checksum: ^1.0.4
  device_info_plus: ^9.0.3
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^4.1.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^4.0.2
  logger: ^2.0.2
  path_provider: ^2.1.1
  sp_util: ^2.0.3
  crypto: ^3.0.3
  convert: ^3.1.1
  path: ^1.8.3
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
